ALTER TABLE "oprema"
ADD COLUMN IF NOT EXISTS "opis" VARCHAR(200),
ADD COLUMN IF NOT EXISTS "serijska_st" VARCHAR(80),
ADD COLUMN IF NOT EXISTS "ustvarjeno" TIMESTAMP(6),
ADD COLUMN IF NOT EXISTS "cena_na_uro" DECIMAL(10,2) NOT NULL DEFAULT 0;
